trigger:
  - none

pr: none

name: $(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool: 'OMS-BUILD'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false